### ISSUE TITLE
FR: Convert (integer) path arguments to string

### ISSUE THREAD

**Issue by MareinK** [firebase/firebase-admin-python#207]
* Operating System version: Arch Linux
  * firebase-admin version: 2.13.0
  * Firebase Product: database

When getting a child reference with an integer, an error is raised.

```
firebase_admin.db.reference(0)
# ValueError: Invalid path: "0". Path must be a string.

firebase_admin.db.reference('users').child(0)
# ValueError: Invalid path argument: "0". Path must be a non-empty string.
```

As a workaround, I wrap `str` around all my integer path arguments. I think it would be nice if firebase-admin could do this conversion for me, at least for integer path arguments, and maybe generally for all arguments.

**Comment by hiranya911** [comment]
We don't try to do type conversions in this library which can result in unexpected behaviors. In your case it is clear that the integer is to be treated as part of the path. But in some cases it could be a programming error. Also what about other values -- booleans, dicts, objects -- all of which have a string representation in Python?

Due to this ambiguity, we require the developers to pass a correct string argument to `db.reference()`.
