### ISSUE TITLE
conflicting cachetools versions

### ISSUE THREAD

**Issue by dgaedcke** [firebase/firebase-admin-python#269]
this project depends upon:
 - google-api-core 
but that requires :
 - google-auth<2.0dev,>=0.4.0

however, google-endpoints requires newer cachetools

so with requirements.txt like this:
- google-endpoints==4.8.0
- firebase-admin  

I'm getting this error:
google-auth 1.6.3 has requirement cachetools>=2.0.0, but you'll have cachetools 1.1.6 which is incompatible.

Collecting protobuf>=3.4.0 (from google-api-core[grpc]<2.0.0dev,>=1.7.0; platform_python_implementation != "PyPy"->firebase-admin->-r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/5e/4b/641b4540ff7ae065c1598c73aacf9cba5d59720e14d39a9d260d50896317/protobuf-3.7.0-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting google-auth<2.0dev,>=0.4.0 (from google-api-core[grpc]<2.0.0dev,>=1.7.0; platform_python_implementation != "PyPy"->firebase-admin->-r requirements.txt (line 16))

**Comment by hiranya911** [comment]
Please report at `google-endpoints` or at `google-endpoints-api-management` so they can upgrade their dependencies:

https://github.com/cloudendpoints/endpoints-management-python/blob/master/setup.py

```
Collecting cachetools<2,>=1.0.0 (from google-endpoints-api-management>=1.10.0->google-endpoints==4.8.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/2a/d8/a3a54933668a0cda92d67c07747be1292555c8ccc28d61e8edf519ea920f/cachetools-1.1.6-py2.py3-none-any.whl
```

`google-auth` depends on v2 of `cachetools`. It's `google-endpoints` that is behind. 

In either case, this cannot be fixed in this repo. Neither `google-endpoints` nor `cachetools` are our direct dependencies.
