### ISSUE TITLE
ImportError: No module named cachetools

### ISSUE THREAD

**Issue by miha93** [firebase/firebase-admin-python#380]
- Operating System version: Ubuntu 16.04.6 LTS
- Firebase SDK version: 3.2.1 or 2.17.0 (tried both)
- Firebase Product: messaging
- Python Version: 2.7.12

whenever I try to import firebase-admin I'm getting the following error
Traceback (most recent call last):
  File "Integrations/firebase.py", line 5, in <module>
    import firebase_admin
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/__init__.py", line 23, in <module>
    from firebase_admin import credentials
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/credentials.py", line 22, in <module>
    from google.oauth2 import credentials
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/credentials.py", line 42, in <module>
    from google.oauth2 import _client
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/_client.py", line 35, in <module>
    from google.auth import jwt
  File "/usr/local/lib/python2.7/dist-packages/google/auth/jwt.py", line 48, in <module>
    import cachetools
ImportError: No module named cachetools

It seems like cachetools has stopped their support with Python2.7 and that's causing the import issue. Any suggestions on what I can try to do to resolve this issue?

**Comment by hiranya911** [comment]
Doesn't reproduce in my development environment:

```
$ virtualenv env -p python

$ source env/bin/activate
(env) $ python
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import firebase_admin
>>> firebase_admin.__version__
'3.2.1'
>>> import cachetools
>>> cachetools.__version__
'3.1.1'
>>> cachetools.__file__
'/home/hiranya/Projects/scratch/env/local/lib/python2.7/site-packages/cachetools/__init__.pyc'
```

As you can see cachetools 3.1.1 was installed along with firebase_admin. This was on Ubuntu 16.

Do you have an installation log, or a sequence of steps I can follow to reproduce this?

**Comment by hiranya911** [comment]
Here's one possible explanation:

* `google-auth` declares the following dependency: `"cachetools>=2.0.0,<5.0"`
* In some environments, this allows the installation to pull in the latest version of cachetools (v4).
* This version seems to have [dropped Python 2 support](https://github.com/tkem/cachetools/commit/aa936f0c2fa997dd648bdc24ec767c57e78482e7#diff-380c6a8ebbbce17d55d50ef17d3cf906).

If this is the case, it needs to be resolved at https://github.com/googleapis/google-auth-library-python by updating their dependency to be `<4.0.0`. But in the meantime you have 2 workarounds:

1. Manually install 3.x version of cachetools.
2. Upgrade to Python 3.

I'd recommend the 2nd option, since Python 2 support is deprecated, and we will also stop supporting is very soon.

**Comment by hiranya911** [comment]
You can continue to track this at https://github.com/googleapis/google-auth-library-python/issues/414
