### ISSUE TITLE
DeprecationWarning from urllib3

### ISSUE THREAD

**Issue by embray** [firebase/firebase-admin-python#515]
### Describe your environment

  * Operating System version: `Linux 78a95de467b6 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 GNU/Linux`
  * Firebase SDK version: admin-python 4.3.0
  * Library version: 4.3.0
  * Firebase Product: auth

#### Steps to reproduce:

urrlib3 version 1.26 introduced a new argument `allowed_methods` to `urllib3.Retry` and deprecated the `method_whitelist` argument, which is still used in [`firebase_admin._http_client`](https://github.com/firebase/firebase-admin-python/blob/ba12bda0d550c33a2831b02ab31a47b32d06aad3/firebase_admin/_http_client.py#L31).

Installing urllib3>=1.26 results in the `DeprecationWarning` when using any part of the library that imports `firebase_admin._http_client`.

Possible solutions:

* Use one spelling or the other depending on detection of urllib3 version
* Pin required version of urllib3<1.26
* Change the argument used here and pin required version of urllib3>=1.26

**Comment by hiranya911** [comment]
We currently don't have a direct dependency on `urllib3`. We just use whatever `requests` provides us.

```py
from requests.packages.urllib3.util import retry
```

It seems `requests` already defines constraints on this dependency, but allows 1.26 of `urllib3`: https://github.com/psf/requests/blob/c2b307dbefe21177af03f9feb37181a89a799fcc/setup.py#L47

I'm currently leaning towards the first option you've suggested. 

```py
from requests.packages import urllib3

_, minor, _ = urllib3.__version__.split('.')
if int(minor) < 26:
  # use old format
else:
  # use new format
```

Will take another close look at this after this after the holidays.

**Comment by xmo-odoo** [comment]
Checking, are there news on the subject?

Also @hiranya911 as-given the solution seems risky: the parameter is slated for removal in urllib3 2.0, which would have a minor version < 26, so going with a version check, the entire thing should probably get checked.

Alternatives:
* inspect the signature of the ctor, and use `allowed_methods` if it's present
* `try` to create the `Retry` object with `allowed_methods`, and fall back on `method_whitelist` if that raises a `TypeError`

Since this is to create a top-level constant, the cost of a try/except should not really be significant.

**Comment by pquentin** [comment]
Right, please sniff features instead of versions. As recommended in https://github.com/urllib3/urllib3/issues/2057#issuecomment-727207327, using this would be safer:

```
use_allowed_methods = hasattr(urllib3.util.Retry.DEFAULT, "allowed_methods")
```

**Comment by hiranya911** [comment]
Would anybody like to send a quick PR for this?

**Comment by xmo-odoo** [comment]
@hiranya911 #532
